### ISSUE TITLE
bro，it seems that this cn.cqautotest.sunnybeach.http.glide.GlideApp, can you take a look

### ISSUE THREAD

**Issue by mokercode** [anjiemo/SunnyBeach#4]
GlideApp could not be found in the project

**Comment by anjiemo** [comment]
你可以尝试 Build -> Clean Project -> Rebuild Project or Make Project，GlideApp 这个类是自动生成的

**Comment by mokercode** [comment]
> 你可以尝试 Build -> Clean Project -> Rebuild Project or Make Project，GlideApp 这个类是自动生成的

thank you very muck！
